require 'csv'

CSV.foreach(Rails.root.join('lib', 'seeds', 'weapons.CSV'), headers: true, col_sep: ';', encoding: 'ISO-8859-1') do |row|
  Weapon.create!(
    name: row['name'],
    price: row['price'],
    size: row['size'],
    ammo_slots: row['ammo_slots'],
    kind: row['kind'],
    bloodline_rank: row['bloodline_rank']
  )
end
puts "Seeded weapons."

CSV.foreach(Rails.root.join('lib', 'seeds', 'tools.CSV'), headers: true, col_sep: ';', encoding: 'ISO-8859-1') do |row|
  Tool.create!(
    name: row['name'],
    price: row['price'],
    kind: row['kind'],
    bloodline_rank: row['bloodline_rank']
  )
end
puts "Seeded tools."

CSV.foreach(Rails.root.join('lib', 'seeds', 'consumables.CSV'), headers: true, col_sep: ';', encoding: 'ISO-8859-1') do |row|
  Consumable.create!(
    name: row['name'],
    price: row['price'],
    kind: row['kind'],
    bloodline_rank: row['bloodline_rank']
  )
end
puts "Seeded consumables."

Ammo.create!(name: "Default", price: 0, weapon_id: 1)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 1)
Ammo.create!(name: "Subsonic", price: 10, weapon_id: 1)
Ammo.create!(name: "Default", price: 0, weapon_id: 2)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 2)
Ammo.create!(name: "Subsonic", price: 10, weapon_id: 2)
Ammo.create!(name: "Default", price: 0, weapon_id: 3)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 3)
Ammo.create!(name: "Subsonic", price: 10, weapon_id: 3)
Ammo.create!(name: "Default", price: 0, weapon_id: 4)
Ammo.create!(name: "Flechette", price: 40, weapon_id: 4)
Ammo.create!(name: "Penny Shot", price: 10, weapon_id: 4)
Ammo.create!(name: "Default", price: 0, weapon_id: 5)
Ammo.create!(name: "Flechette", price: 40, weapon_id: 5)
Ammo.create!(name: "Penny Shot", price: 10, weapon_id: 5)
Ammo.create!(name: "Default", price: 0, weapon_id: 7)
Ammo.create!(name: "Incendiary", price: 35, weapon_id: 7)
Ammo.create!(name: "Spitzer", price: 75, weapon_id: 7)
Ammo.create!(name: "Default", price: 0, weapon_id: 8)
Ammo.create!(name: "Incendiary", price: 35, weapon_id: 8)
Ammo.create!(name: "Spitzer", price: 75, weapon_id: 8)
Ammo.create!(name: "Default", price: 0, weapon_id: 9)
Ammo.create!(name: "Incendiary", price: 35, weapon_id: 9)
Ammo.create!(name: "Spitzer", price: 75, weapon_id: 9)
Ammo.create!(name: "Default", price: 0, weapon_id: 10)
Ammo.create!(name: "Incendiary", price: 35, weapon_id: 10)
Ammo.create!(name: "Spitzer", price: 75, weapon_id: 10)
Ammo.create!(name: "Default", price: 0, weapon_id: 11)
Ammo.create!(name: "Dragon Breath", price: 10, weapon_id: 11)
Ammo.create!(name: "Harpoon", price: 5, weapon_id: 11)
Ammo.create!(name: "Steel Ball", price: 5, weapon_id: 11)
Ammo.create!(name: "Waxed Frag Charge", price: 50, weapon_id: 11)
Ammo.create!(name: "Default", price: 0, weapon_id: 12)
Ammo.create!(name: "Dragon Breath", price: 10, weapon_id: 12)
Ammo.create!(name: "Harpoon", price: 5, weapon_id: 12)
Ammo.create!(name: "Steel Ball", price: 5, weapon_id: 12)
Ammo.create!(name: "Waxed Frag Charge", price: 50, weapon_id: 12)
Ammo.create!(name: "Default", price: 0, weapon_id: 13)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 13)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 13)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 13)
Ammo.create!(name: "Default", price: 0, weapon_id: 14)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 14)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 14)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 14)
Ammo.create!(name: "Default", price: 0, weapon_id: 15)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 15)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 15)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 15)
Ammo.create!(name: "Default", price: 0, weapon_id: 16)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 16)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 16)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 16)
Ammo.create!(name: "Default", price: 0, weapon_id: 17)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 17)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 17)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 17)
Ammo.create!(name: "Default", price: 0, weapon_id: 18)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 18)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 18)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 18)
Ammo.create!(name: "Default", price: 0, weapon_id: 19)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 19)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 19)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 19)
Ammo.create!(name: "Default", price: 0, weapon_id: 21)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 21)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 21)
Ammo.create!(name: "Poison", price: 50, weapon_id: 21)
Ammo.create!(name: "Subsonic", price: 10, weapon_id: 21)
Ammo.create!(name: "Default", price: 0, weapon_id: 22)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 22)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 22)
Ammo.create!(name: "Poison", price: 50, weapon_id: 22)
Ammo.create!(name: "Subsonic", price: 10, weapon_id: 22)
Ammo.create!(name: "Default", price: 0, weapon_id: 23)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 23)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 23)
Ammo.create!(name: "Poison", price: 50, weapon_id: 23)
Ammo.create!(name: "Subsonic", price: 10, weapon_id: 23)
Ammo.create!(name: "Default", price: 0, weapon_id: 24)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 24)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 24)
Ammo.create!(name: "Poison", price: 50, weapon_id: 24)
Ammo.create!(name: "Subsonic", price: 10, weapon_id: 24)
Ammo.create!(name: "Default", price: 0, weapon_id: 25)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 25)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 25)
Ammo.create!(name: "Poison", price: 50, weapon_id: 25)
Ammo.create!(name: "Subsonic", price: 10, weapon_id: 25)
Ammo.create!(name: "Default", price: 0, weapon_id: 26)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 26)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 26)
Ammo.create!(name: "Poison", price: 50, weapon_id: 26)
Ammo.create!(name: "Subsonic", price: 10, weapon_id: 26)
Ammo.create!(name: "Default", price: 0, weapon_id: 27)
Ammo.create!(name: "Explosive", price: 50, weapon_id: 27)
Ammo.create!(name: "Incendiary", price: 25, weapon_id: 27)
Ammo.create!(name: "Default", price: 0, weapon_id: 29)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 29)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 29)
Ammo.create!(name: "Default", price: 0, weapon_id: 30)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 30)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 30)
Ammo.create!(name: "Default", price: 0, weapon_id: 31)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 31)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 31)
Ammo.create!(name: "Default", price: 0, weapon_id: 32)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 32)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 32)
Ammo.create!(name: "Default", price: 0, weapon_id: 33)
Ammo.create!(name: "Explosive", price: 35, weapon_id: 33)
Ammo.create!(name: "Shot", price: 40, weapon_id: 33)
Ammo.create!(name: "Steel", price: 40, weapon_id: 33)
Ammo.create!(name: "Default", price: 0, weapon_id: 34)
Ammo.create!(name: "Explosive", price: 35, weapon_id: 34)
Ammo.create!(name: "Shot", price: 40, weapon_id: 34)
Ammo.create!(name: "Steel", price: 40, weapon_id: 34)
Ammo.create!(name: "Default", price: 0, weapon_id: 35)
Ammo.create!(name: "Default", price: 0, weapon_id: 36)
Ammo.create!(name: "Default", price: 0, weapon_id: 37)
Ammo.create!(name: "Default", price: 0, weapon_id: 38)
Ammo.create!(name: "Default", price: 0, weapon_id: 39)
Ammo.create!(name: "Default", price: 0, weapon_id: 40)
Ammo.create!(name: "Default", price: 0, weapon_id: 41)
Ammo.create!(name: "Default", price: 0, weapon_id: 42, pool: 1)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 42, pool: 1)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 42, pool: 1)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 42, pool: 1)
Ammo.create!(name: "Default", price: 0, weapon_id: 42, pool: 2)
Ammo.create!(name: "Flechette", price: 20, weapon_id: 42, pool: 2)
Ammo.create!(name: "Penny Shot", price: 5, weapon_id: 42, pool: 2)
Ammo.create!(name: "Slug", price: 65, weapon_id: 42, pool: 2)
Ammo.create!(name: "Default", price: 0, weapon_id: 43, pool: 1)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 43, pool: 1)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 43, pool: 1)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 43, pool: 1)
Ammo.create!(name: "Default", price: 0, weapon_id: 43, pool: 2)
Ammo.create!(name: "Flechette", price: 20, weapon_id: 43, pool: 2)
Ammo.create!(name: "Penny Shot", price: 5, weapon_id: 43, pool: 2)
Ammo.create!(name: "Slug", price: 65, weapon_id: 43, pool: 2)
Ammo.create!(name: "Default", price: 0, weapon_id: 44, pool: 1)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 44, pool: 1)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 44, pool: 1)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 44, pool: 1)
Ammo.create!(name: "Default", price: 0, weapon_id: 44, pool: 2)
Ammo.create!(name: "Flechette", price: 20, weapon_id: 44, pool: 2)
Ammo.create!(name: "Penny Shot", price: 5, weapon_id: 44, pool: 2)
Ammo.create!(name: "Slug", price: 65, weapon_id: 44, pool: 2)
Ammo.create!(name: "Default", price: 0, weapon_id: 45)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 45)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 45)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 45)
Ammo.create!(name: "Poison", price: 50, weapon_id: 45)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 45)
Ammo.create!(name: "Default", price: 0, weapon_id: 46)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 46)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 46)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 46)
Ammo.create!(name: "Poison", price: 50, weapon_id: 46)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 46)
Ammo.create!(name: "Default", price: 0, weapon_id: 47)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 47)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 47)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 47)
Ammo.create!(name: "Poison", price: 50, weapon_id: 47)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 47)
Ammo.create!(name: "Default", price: 0, weapon_id: 48)
Ammo.create!(name: "Chaos", price: 10, weapon_id: 48)
Ammo.create!(name: "Choke", price: 10, weapon_id: 48)
Ammo.create!(name: "Dragon", price: 40, weapon_id: 48)
Ammo.create!(name: "Poison", price: 25, weapon_id: 48)
Ammo.create!(name: "Default", price: 0, weapon_id: 49, pool: 1)
Ammo.create!(name: "FMJ", price: 60, weapon_id: 49, pool: 1)
Ammo.create!(name: "Poison", price: 60, weapon_id: 49, pool: 1)
Ammo.create!(name: "Default", price: 0, weapon_id: 49, pool: 2)
Ammo.create!(name: "Dragon Breath", price: 10, weapon_id: 49, pool: 2)
Ammo.create!(name: "Slug", price: 0, weapon_id: 65, pool: 2)
Ammo.create!(name: "Starshell", price: 5, weapon_id: 49, pool: 2)
Ammo.create!(name: "Default", price: 0, weapon_id: 50)
Ammo.create!(name: "Concertina", price: 30, weapon_id: 50)
Ammo.create!(name: "Frag", price: 70, weapon_id: 50)
Ammo.create!(name: "Poison", price: 25, weapon_id: 50)
Ammo.create!(name: "Default", price: 0, weapon_id: 51)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 51)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 51)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 51)
Ammo.create!(name: "Poison", price: 50, weapon_id: 51)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 51)
Ammo.create!(name: "Default", price: 0, weapon_id: 52)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 52)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 52)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 52)
Ammo.create!(name: "Poison", price: 50, weapon_id: 52)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 52)
Ammo.create!(name: "Default", price: 0, weapon_id: 53)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 53)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 53)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 53)
Ammo.create!(name: "Poison", price: 50, weapon_id: 53)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 53)
Ammo.create!(name: "Default", price: 0, weapon_id: 55)
Ammo.create!(name: "FMJ", price: 60, weapon_id: 55)
Ammo.create!(name: "Incendiary", price: 70, weapon_id: 55)
Ammo.create!(name: "Subsonic", price: 20, weapon_id: 55)
Ammo.create!(name: "Default", price: 0, weapon_id: 56)
Ammo.create!(name: "FMJ", price: 60, weapon_id: 56)
Ammo.create!(name: "Incendiary", price: 70, weapon_id: 56)
Ammo.create!(name: "Subsonic", price: 20, weapon_id: 56)
Ammo.create!(name: "Default", price: 0, weapon_id: 57)
Ammo.create!(name: "FMJ", price: 60, weapon_id: 57)
Ammo.create!(name: "Incendiary", price: 70, weapon_id: 57)
Ammo.create!(name: "Subsonic", price: 20, weapon_id: 57)
Ammo.create!(name: "Default", price: 0, weapon_id: 58)
Ammo.create!(name: "FMJ", price: 60, weapon_id: 58)
Ammo.create!(name: "Incendiary", price: 70, weapon_id: 58)
Ammo.create!(name: "Subsonic", price: 20, weapon_id: 58)
Ammo.create!(name: "Default", price: 0, weapon_id: 59, pool: 1)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 59, pool: 1)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 59, pool: 1)
Ammo.create!(name: "Default", price: 0, weapon_id: 59, pool: 2)
Ammo.create!(name: "Draon Breath", price: 10, weapon_id: 59, pool: 2)
Ammo.create!(name: "Slug", price: 65, weapon_id: 59, pool: 2)
Ammo.create!(name: "Starshell", price: 5, weapon_id: 59, pool: 2)
Ammo.create!(name: "Default", price: 0, weapon_id: 60, pool: 1)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 60, pool: 1)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 60, pool: 1)
Ammo.create!(name: "Default", price: 0, weapon_id: 60, pool: 2)
Ammo.create!(name: "Draon Breath", price: 10, weapon_id: 60, pool: 2)
Ammo.create!(name: "Slug", price: 65, weapon_id: 60, pool: 2)
Ammo.create!(name: "Starshell", price: 5, weapon_id: 60, pool: 2)
Ammo.create!(name: "Default", price: 0, weapon_id: 61, pool: 1)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 61, pool: 1)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 61, pool: 1)
Ammo.create!(name: "Default", price: 0, weapon_id: 61, pool: 2)
Ammo.create!(name: "Draon Breath", price: 10, weapon_id: 61, pool: 2)
Ammo.create!(name: "Slug", price: 65, weapon_id: 61, pool: 2)
Ammo.create!(name: "Starshell", price: 5, weapon_id: 61, pool: 2)
Ammo.create!(name: "Default", price: 0, weapon_id: 62, pool: 1)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 62, pool: 1)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 62, pool: 1)
Ammo.create!(name: "Default", price: 0, weapon_id: 62, pool: 2)
Ammo.create!(name: "Draon Breath", price: 10, weapon_id: 62, pool: 2)
Ammo.create!(name: "Slug", price: 65, weapon_id: 62, pool: 2)
Ammo.create!(name: "Starshell", price: 5, weapon_id: 62, pool: 2)
Ammo.create!(name: "Default", price: 0, weapon_id: 63)
Ammo.create!(name: "Incendiary", price: 70, weapon_id: 63)
Ammo.create!(name: "Spitzer", price: 150, weapon_id: 63)
Ammo.create!(name: "Default", price: 0, weapon_id: 64)
Ammo.create!(name: "Incendiary", price: 70, weapon_id: 64)
Ammo.create!(name: "Spitzer", price: 150, weapon_id: 64)
Ammo.create!(name: "Default", price: 0, weapon_id: 65)
Ammo.create!(name: "Incendiary", price: 70, weapon_id: 65)
Ammo.create!(name: "Spitzer", price: 150, weapon_id: 65)
Ammo.create!(name: "Default", price: 0, weapon_id: 66)
Ammo.create!(name: "Incendiary", price: 70, weapon_id: 66)
Ammo.create!(name: "Spitzer", price: 150, weapon_id: 66)
Ammo.create!(name: "Default", price: 0, weapon_id: 68)
Ammo.create!(name: "Explosive", price: 100, weapon_id: 68)
Ammo.create!(name: "FMJ", price: 60, weapon_id: 68)
Ammo.create!(name: "Default", price: 0, weapon_id: 69)
Ammo.create!(name: "Explosive", price: 100, weapon_id: 69)
Ammo.create!(name: "FMJ", price: 60, weapon_id: 69)
Ammo.create!(name: "Default", price: 0, weapon_id: 70)
Ammo.create!(name: "Explosive", price: 100, weapon_id: 70)
Ammo.create!(name: "FMJ", price: 60, weapon_id: 70)
Ammo.create!(name: "Default", price: 0, weapon_id: 71)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 71)
Ammo.create!(name: "High Velocity", price: 50, weapon_id: 71)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 71)
Ammo.create!(name: "Poison", price: 50, weapon_id: 71)
Ammo.create!(name: "Default", price: 0, weapon_id: 72)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 72)
Ammo.create!(name: "High Velocity", price: 50, weapon_id: 72)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 72)
Ammo.create!(name: "Poison", price: 50, weapon_id: 72)
Ammo.create!(name: "Default", price: 0, weapon_id: 73)
Ammo.create!(name: "Explosive", price: 50, weapon_id: 73)
Ammo.create!(name: "FMJ", price: 30, weapon_id: 73)
Ammo.create!(name: "High Velocity", price: 35, weapon_id: 73)
Ammo.create!(name: "Incendiary", price: 35, weapon_id: 73)
Ammo.create!(name: "Default", price: 0, weapon_id: 74)
Ammo.create!(name: "Explosive", price: 50, weapon_id: 74)
Ammo.create!(name: "FMJ", price: 30, weapon_id: 74)
Ammo.create!(name: "High Velocity", price: 35, weapon_id: 74)
Ammo.create!(name: "Incendiary", price: 35, weapon_id: 74)
Ammo.create!(name: "Default", price: 0, weapon_id: 75)
Ammo.create!(name: "Explosive", price: 50, weapon_id: 75)
Ammo.create!(name: "FMJ", price: 30, weapon_id: 75)
Ammo.create!(name: "High Velocity", price: 35, weapon_id: 75)
Ammo.create!(name: "Incendiary", price: 35, weapon_id: 75)
Ammo.create!(name: "Default", price: 0, weapon_id: 76)
Ammo.create!(name: "Explosive", price: 50, weapon_id: 76)
Ammo.create!(name: "FMJ", price: 30, weapon_id: 76)
Ammo.create!(name: "High Velocity", price: 35, weapon_id: 76)
Ammo.create!(name: "Incendiary", price: 35, weapon_id: 76)
Ammo.create!(name: "Default", price: 0, weapon_id: 77)
Ammo.create!(name: "Explosive", price: 50, weapon_id: 77)
Ammo.create!(name: "FMJ", price: 30, weapon_id: 77)
Ammo.create!(name: "High Velocity", price: 35, weapon_id: 77)
Ammo.create!(name: "Incendiary", price: 35, weapon_id: 77)
Ammo.create!(name: "Default", price: 0, weapon_id: 78)
Ammo.create!(name: "High Velocity", price: 30, weapon_id: 78)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 78)
Ammo.create!(name: "Default", price: 0, weapon_id: 79)
Ammo.create!(name: "High Velocity", price: 30, weapon_id: 79)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 79)
Ammo.create!(name: "Default", price: 0, weapon_id: 80)
Ammo.create!(name: "Incendiary", price: 70, weapon_id: 80)
Ammo.create!(name: "Spitzer", price: 150, weapon_id: 80)
Ammo.create!(name: "Default", price: 0, weapon_id: 81)
Ammo.create!(name: "Incendiary", price: 70, weapon_id: 81)
Ammo.create!(name: "Spitzer", price: 150, weapon_id: 81)
Ammo.create!(name: "Default", price: 0, weapon_id: 82)
Ammo.create!(name: "Incendiary", price: 70, weapon_id: 82)
Ammo.create!(name: "Spitzer", price: 150, weapon_id: 82)
Ammo.create!(name: "Default", price: 0, weapon_id: 83)
Ammo.create!(name: "Incendiary", price: 70, weapon_id: 83)
Ammo.create!(name: "Spitzer", price: 150, weapon_id: 83)
Ammo.create!(name: "Default", price: 0, weapon_id: 84)
Ammo.create!(name: "Incendiary", price: 70, weapon_id: 84)
Ammo.create!(name: "Spitzer", price: 150, weapon_id: 84)
Ammo.create!(name: "Default", price: 0, weapon_id: 85)
Ammo.create!(name: "Incendiary", price: 70, weapon_id: 85)
Ammo.create!(name: "Spitzer", price: 150, weapon_id: 85)
Ammo.create!(name: "Default", price: 0, weapon_id: 86)
Ammo.create!(name: "Incendiary", price: 70, weapon_id: 86)
Ammo.create!(name: "Spitzer", price: 150, weapon_id: 86)
Ammo.create!(name: "Default", price: 0, weapon_id: 87)
Ammo.create!(name: "Incendiary", price: 70, weapon_id: 87)
Ammo.create!(name: "Spitzer", price: 150, weapon_id: 87)
Ammo.create!(name: "Default", price: 0, weapon_id: 88)
Ammo.create!(name: "Incendiary", price: 70, weapon_id: 88)
Ammo.create!(name: "Spitzer", price: 150, weapon_id: 88)
Ammo.create!(name: "Default", price: 0, weapon_id: 89)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 89)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 89)
Ammo.create!(name: "Poison", price: 50, weapon_id: 89)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 89)
Ammo.create!(name: "Default", price: 0, weapon_id: 90)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 90)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 90)
Ammo.create!(name: "Poison", price: 50, weapon_id: 90)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 90)
Ammo.create!(name: "Default", price: 0, weapon_id: 91)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 91)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 91)
Ammo.create!(name: "Poison", price: 50, weapon_id: 91)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 91)
Ammo.create!(name: "Default", price: 0, weapon_id: 92)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 92)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 92)
Ammo.create!(name: "Poison", price: 50, weapon_id: 92)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 92)
Ammo.create!(name: "Default", price: 0, weapon_id: 93)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 93)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 93)
Ammo.create!(name: "Poison", price: 50, weapon_id: 93)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 93)
Ammo.create!(name: "Default", price: 0, weapon_id: 94)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 94)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 94)
Ammo.create!(name: "Poison", price: 50, weapon_id: 94)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 94)
Ammo.create!(name: "Default", price: 0, weapon_id: 95)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 95)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 95)
Ammo.create!(name: "Default", price: 0, weapon_id: 96)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 96)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 96)
Ammo.create!(name: "Default", price: 0, weapon_id: 97)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 97)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 97)
Ammo.create!(name: "Default", price: 0, weapon_id: 98)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 98)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 98)
Ammo.create!(name: "Default", price: 0, weapon_id: 99)
Ammo.create!(name: "Explosive", price: 200, weapon_id: 99)
Ammo.create!(name: "Shredder", price: 225, weapon_id: 99)
Ammo.create!(name: "Default", price: 0, weapon_id: 100)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 100)
Ammo.create!(name: "Poison", price: 50, weapon_id: 100)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 100)
Ammo.create!(name: "Default", price: 0, weapon_id: 101)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 101)
Ammo.create!(name: "Poison", price: 50, weapon_id: 101)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 101)
Ammo.create!(name: "Default", price: 0, weapon_id: 102)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 102)
Ammo.create!(name: "Poison", price: 50, weapon_id: 102)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 102)
Ammo.create!(name: "Default", price: 0, weapon_id: 103)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 103)
Ammo.create!(name: "Poison", price: 50, weapon_id: 103)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 103)
Ammo.create!(name: "Default", price: 0, weapon_id: 104)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 104)
Ammo.create!(name: "Poison", price: 50, weapon_id: 104)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 104)
Ammo.create!(name: "Default", price: 0, weapon_id: 105)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 105)
Ammo.create!(name: "Poison", price: 50, weapon_id: 105)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 105)
Ammo.create!(name: "Default", price: 0, weapon_id: 106)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 106)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 106)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 106)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 106)
Ammo.create!(name: "Poison", price: 50, weapon_id: 106)
Ammo.create!(name: "Default", price: 0, weapon_id: 107)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 107)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 107)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 107)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 107)
Ammo.create!(name: "Poison", price: 50, weapon_id: 107)
Ammo.create!(name: "Default", price: 0, weapon_id: 108)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 108)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 108)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 108)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 108)
Ammo.create!(name: "Poison", price: 50, weapon_id: 108)
Ammo.create!(name: "Default", price: 0, weapon_id: 109)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 109)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 109)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 109)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 109)
Ammo.create!(name: "Poison", price: 50, weapon_id: 109)
Ammo.create!(name: "Default", price: 0, weapon_id: 110)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 110)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 110)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 110)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 110)
Ammo.create!(name: "Poison", price: 50, weapon_id: 110)
Ammo.create!(name: "Default", price: 0, weapon_id: 111)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 111)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 111)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 111)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 111)
Ammo.create!(name: "Poison", price: 50, weapon_id: 111)
Ammo.create!(name: "Default", price: 0, weapon_id: 113)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 113)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 113)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 113)
Ammo.create!(name: "Poison", price: 50, weapon_id: 113)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 113)
Ammo.create!(name: "Default", price: 0, weapon_id: 114)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 114)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 114)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 114)
Ammo.create!(name: "Poison", price: 50, weapon_id: 114)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 114)
Ammo.create!(name: "Default", price: 0, weapon_id: 114)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 114)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 114)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 114)
Ammo.create!(name: "Poison", price: 50, weapon_id: 114)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 114)
Ammo.create!(name: "Default", price: 0, weapon_id: 115)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 115)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 115)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 115)
Ammo.create!(name: "Poison", price: 50, weapon_id: 115)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 115)
Ammo.create!(name: "Default", price: 0, weapon_id: 116)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 116)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 116)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 116)
Ammo.create!(name: "Poison", price: 50, weapon_id: 116)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 116)
Ammo.create!(name: "Default", price: 0, weapon_id: 117)
Ammo.create!(name: "Dragon Breath", price: 20, weapon_id: 117)
Ammo.create!(name: "Flechette", price: 40, weapon_id: 117)
Ammo.create!(name: "Penny Shot", price: 10, weapon_id: 117)
Ammo.create!(name: "Slug", price: 130, weapon_id: 117)
Ammo.create!(name: "Default", price: 0, weapon_id: 118)
Ammo.create!(name: "Dragon Breath", price: 20, weapon_id: 118)
Ammo.create!(name: "Flechette", price: 40, weapon_id: 118)
Ammo.create!(name: "Penny Shot", price: 10, weapon_id: 118)
Ammo.create!(name: "Slug", price: 130, weapon_id: 118)
Ammo.create!(name: "Default", price: 0, weapon_id: 119)
Ammo.create!(name: "Dragon Breath", price: 20, weapon_id: 119)
Ammo.create!(name: "Flechette", price: 40, weapon_id: 119)
Ammo.create!(name: "Penny Shot", price: 10, weapon_id: 119)
Ammo.create!(name: "Slug", price: 130, weapon_id: 119)
Ammo.create!(name: "Default", price: 0, weapon_id: 120)
Ammo.create!(name: "Dragon Breath", price: 20, weapon_id: 120)
Ammo.create!(name: "Flechette", price: 40, weapon_id: 120)
Ammo.create!(name: "Penny Shot", price: 10, weapon_id: 120)
Ammo.create!(name: "Slug", price: 130, weapon_id: 120)
Ammo.create!(name: "Default", price: 0, weapon_id: 121)
Ammo.create!(name: "Dragon Breath", price: 10, weapon_id: 121)
Ammo.create!(name: "Penny Shot", price: 5, weapon_id: 121)
Ammo.create!(name: "Slug", price: 65, weapon_id: 121)
Ammo.create!(name: "Starshell", price: 5, weapon_id: 121)
Ammo.create!(name: "Default", price: 0, weapon_id: 122)
Ammo.create!(name: "Dragon Breath", price: 10, weapon_id: 122)
Ammo.create!(name: "Penny Shot", price: 5, weapon_id: 122)
Ammo.create!(name: "Slug", price: 65, weapon_id: 122)
Ammo.create!(name: "Starshell", price: 5, weapon_id: 122)
Ammo.create!(name: "Default", price: 0, weapon_id: 122)
Ammo.create!(name: "Dragon Breath", price: 10, weapon_id: 123)
Ammo.create!(name: "Penny Shot", price: 5, weapon_id: 123)
Ammo.create!(name: "Slug", price: 65, weapon_id: 123)
Ammo.create!(name: "Starshell", price: 5, weapon_id: 123)
Ammo.create!(name: "Default", price: 0, weapon_id: 124)
Ammo.create!(name: "Dragon Breath", price: 10, weapon_id: 124)
Ammo.create!(name: "Penny Shot", price: 5, weapon_id: 124)
Ammo.create!(name: "Slug", price: 65, weapon_id: 124)
Ammo.create!(name: "Starshell", price: 5, weapon_id: 124)
Ammo.create!(name: "Default", price: 0, weapon_id: 125)
Ammo.create!(name: "Dragon Breath", price: 10, weapon_id: 125)
Ammo.create!(name: "Penny Shot", price: 5, weapon_id: 125)
Ammo.create!(name: "Slug", price: 65, weapon_id: 125)
Ammo.create!(name: "Starshell", price: 5, weapon_id: 125)
Ammo.create!(name: "Default", price: 0, weapon_id: 126)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 126)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 126)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 126)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 126)
Ammo.create!(name: "Default", price: 0, weapon_id: 127)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 127)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 127)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 127)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 127)
Ammo.create!(name: "Default", price: 0, weapon_id: 128)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 128)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 128)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 128)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 128)
Ammo.create!(name: "Default", price: 0, weapon_id: 129)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 129)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 129)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 129)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 129)
Ammo.create!(name: "Default", price: 0, weapon_id: 130)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 130)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 130)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 130)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 130)
Ammo.create!(name: "Default", price: 0, weapon_id: 131)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 131)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 131)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 131)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 131)
Ammo.create!(name: "Default", price: 0, weapon_id: 132)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 132)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 132)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 132)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 132)
Ammo.create!(name: "Default", price: 0, weapon_id: 133)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 133)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 133)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 133)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 133)
Ammo.create!(name: "Default", price: 0, weapon_id: 134)
Ammo.create!(name: "Dumdum", price: 50, weapon_id: 134)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 134)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 134)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 134)
Ammo.create!(name: "Default", price: 0, weapon_id: 135)
Ammo.create!(name: "Penny Shot", price: 10, weapon_id: 135)
Ammo.create!(name: "Slug", price: 135, weapon_id: 135)
Ammo.create!(name: "Default", price: 0, weapon_id: 136)
Ammo.create!(name: "Penny Shot", price: 10, weapon_id: 136)
Ammo.create!(name: "Slug", price: 135, weapon_id: 136)
Ammo.create!(name: "Default", price: 0, weapon_id: 137)
Ammo.create!(name: "FMJ", price: 30, weapon_id: 137)
Ammo.create!(name: "Incendiary", price: 35, weapon_id: 137)
Ammo.create!(name: "Poison", price: 30, weapon_id: 137)
Ammo.create!(name: "Subsonic", price: 10, weapon_id: 137)
Ammo.create!(name: "Default", price: 0, weapon_id: 138)
Ammo.create!(name: "FMJ", price: 30, weapon_id: 138)
Ammo.create!(name: "Incendiary", price: 35, weapon_id: 138)
Ammo.create!(name: "Poison", price: 30, weapon_id: 138)
Ammo.create!(name: "Subsonic", price: 10, weapon_id: 138)
Ammo.create!(name: "Default", price: 0, weapon_id: 139)
Ammo.create!(name: "FMJ", price: 30, weapon_id: 139)
Ammo.create!(name: "Incendiary", price: 35, weapon_id: 139)
Ammo.create!(name: "Poison", price: 30, weapon_id: 139)
Ammo.create!(name: "Subsonic", price: 10, weapon_id: 139)
Ammo.create!(name: "Default", price: 0, weapon_id: 140)
Ammo.create!(name: "FMJ", price: 30, weapon_id: 140)
Ammo.create!(name: "Incendiary", price: 35, weapon_id: 140)
Ammo.create!(name: "Poison", price: 30, weapon_id: 140)
Ammo.create!(name: "Subsonic", price: 10, weapon_id: 140)
Ammo.create!(name: "Default", price: 0, weapon_id: 141)
Ammo.create!(name: "FMJ", price: 30, weapon_id: 141)
Ammo.create!(name: "Incendiary", price: 35, weapon_id: 141)
Ammo.create!(name: "Poison", price: 30, weapon_id: 141)
Ammo.create!(name: "Subsonic", price: 10, weapon_id: 141)
Ammo.create!(name: "Default", price: 0, weapon_id: 142)
Ammo.create!(name: "FMJ", price: 30, weapon_id: 142)
Ammo.create!(name: "Incendiary", price: 35, weapon_id: 142)
Ammo.create!(name: "Poison", price: 30, weapon_id: 142)
Ammo.create!(name: "Subsonic", price: 10, weapon_id: 142)
Ammo.create!(name: "Default", price: 0, weapon_id: 143)
Ammo.create!(name: "Dragon Breath", price: 20, weapon_id: 143)
Ammo.create!(name: "Flechette", price: 40, weapon_id: 143)
Ammo.create!(name: "Penny Shot", price: 10, weapon_id: 143)
Ammo.create!(name: "Slug", price: 130, weapon_id: 143)
Ammo.create!(name: "Default", price: 0, weapon_id: 144)
Ammo.create!(name: "Dragon Breath", price: 20, weapon_id: 144)
Ammo.create!(name: "Flechette", price: 40, weapon_id: 144)
Ammo.create!(name: "Penny Shot", price: 10, weapon_id: 144)
Ammo.create!(name: "Slug", price: 130, weapon_id: 144)
Ammo.create!(name: "Default", price: 0, weapon_id: 145)
Ammo.create!(name: "Dragon Breath", price: 20, weapon_id: 145)
Ammo.create!(name: "Flechette", price: 40, weapon_id: 145)
Ammo.create!(name: "Penny Shot", price: 10, weapon_id: 145)
Ammo.create!(name: "Slug", price: 130, weapon_id: 145)
Ammo.create!(name: "Default", price: 0, weapon_id: 146)
Ammo.create!(name: "Dumdum", price: 25, weapon_id: 146)
Ammo.create!(name: "Explosive", price: 45, weapon_id: 146)
Ammo.create!(name: "High Velocity", price: 30, weapon_id: 146)
Ammo.create!(name: "Poison", price: 25, weapon_id: 146)
Ammo.create!(name: "Default", price: 0, weapon_id: 147)
Ammo.create!(name: "Dumdum", price: 25, weapon_id: 147)
Ammo.create!(name: "Explosive", price: 45, weapon_id: 147)
Ammo.create!(name: "High Velocity", price: 30, weapon_id: 147)
Ammo.create!(name: "Poison", price: 25, weapon_id: 147)
Ammo.create!(name: "Default", price: 0, weapon_id: 148)
Ammo.create!(name: "Dumdum", price: 25, weapon_id: 148)
Ammo.create!(name: "Explosive", price: 45, weapon_id: 148)
Ammo.create!(name: "High Velocity", price: 30, weapon_id: 148)
Ammo.create!(name: "Poison", price: 25, weapon_id: 148)
Ammo.create!(name: "Default", price: 0, weapon_id: 149)
Ammo.create!(name: "Dumdum", price: 25, weapon_id: 149)
Ammo.create!(name: "Explosive", price: 45, weapon_id: 149)
Ammo.create!(name: "High Velocity", price: 30, weapon_id: 149)
Ammo.create!(name: "Poison", price: 25, weapon_id: 149)
Ammo.create!(name: "Default", price: 0, weapon_id: 150)
Ammo.create!(name: "Dumdum", price: 25, weapon_id: 150)
Ammo.create!(name: "Explosive", price: 45, weapon_id: 150)
Ammo.create!(name: "High Velocity", price: 30, weapon_id: 150)
Ammo.create!(name: "Poison", price: 25, weapon_id: 150)
Ammo.create!(name: "Default", price: 0, weapon_id: 151)
Ammo.create!(name: "Dumdum", price: 25, weapon_id: 151)
Ammo.create!(name: "Explosive", price: 45, weapon_id: 151)
Ammo.create!(name: "High Velocity", price: 30, weapon_id: 151)
Ammo.create!(name: "Poison", price: 25, weapon_id: 151)
Ammo.create!(name: "Default", price: 0, weapon_id: 152)
Ammo.create!(name: "Dragon Breath", price: 20, weapon_id: 152)
Ammo.create!(name: "Flechette", price: 40, weapon_id: 152)
Ammo.create!(name: "Penny Shot", price: 10, weapon_id: 152)
Ammo.create!(name: "Slug", price: 130, weapon_id: 152)
Ammo.create!(name: "Default", price: 0, weapon_id: 153)
Ammo.create!(name: "Dragon Breath", price: 20, weapon_id: 153)
Ammo.create!(name: "Flechette", price: 40, weapon_id: 153)
Ammo.create!(name: "Penny Shot", price: 10, weapon_id: 153)
Ammo.create!(name: "Slug", price: 130, weapon_id: 153)
Ammo.create!(name: "Default", price: 0, weapon_id: 154)
Ammo.create!(name: "Exploxive", price: 100, weapon_id: 154)
Ammo.create!(name: "FMJ", price: 60, weapon_id: 154)
Ammo.create!(name: "Incendiary", price: 70, weapon_id: 154)
Ammo.create!(name: "Default", price: 0, weapon_id: 155)
Ammo.create!(name: "Exploxive", price: 100, weapon_id: 155)
Ammo.create!(name: "FMJ", price: 60, weapon_id: 155)
Ammo.create!(name: "Incendiary", price: 70, weapon_id: 155)
Ammo.create!(name: "Default", price: 0, weapon_id: 156)
Ammo.create!(name: "Exploxive", price: 100, weapon_id: 156)
Ammo.create!(name: "FMJ", price: 60, weapon_id: 156)
Ammo.create!(name: "Incendiary", price: 70, weapon_id: 156)
Ammo.create!(name: "Default", price: 0, weapon_id: 157)
Ammo.create!(name: "Exploxive", price: 100, weapon_id: 157)
Ammo.create!(name: "FMJ", price: 60, weapon_id: 157)
Ammo.create!(name: "Incendiary", price: 70, weapon_id: 157)
Ammo.create!(name: "Default", price: 0, weapon_id: 158)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 158)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 158)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 158)
Ammo.create!(name: "Poison", price: 50, weapon_id: 158)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 158)
Ammo.create!(name: "Default", price: 0, weapon_id: 159)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 159)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 159)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 159)
Ammo.create!(name: "Poison", price: 50, weapon_id: 159)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 159)
Ammo.create!(name: "Default", price: 0, weapon_id: 160)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 160)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 160)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 160)
Ammo.create!(name: "Poison", price: 50, weapon_id: 160)
Ammo.create!(name: "Subsonic", price: 5, weapon_id: 160)
Ammo.create!(name: "Default", price: 0, weapon_id: 161)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 161)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 161)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 161)
Ammo.create!(name: "Subsonic", price: 10, weapon_id: 161)
Ammo.create!(name: "Default", price: 0, weapon_id: 162)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 162)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 162)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 162)
Ammo.create!(name: "Subsonic", price: 10, weapon_id: 162)
Ammo.create!(name: "Default", price: 0, weapon_id: 163)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 163)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 163)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 163)
Ammo.create!(name: "Subsonic", price: 10, weapon_id: 163)
Ammo.create!(name: "Default", price: 0, weapon_id: 164)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 164)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 164)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 164)
Ammo.create!(name: "Subsonic", price: 10, weapon_id: 164)
Ammo.create!(name: "Default", price: 0, weapon_id: 165)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 165)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 165)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 165)
Ammo.create!(name: "Subsonic", price: 10, weapon_id: 165)
Ammo.create!(name: "Default", price: 0, weapon_id: 166)
Ammo.create!(name: "FMJ", price: 50, weapon_id: 166)
Ammo.create!(name: "High Velocity", price: 60, weapon_id: 166)
Ammo.create!(name: "Incendiary", price: 40, weapon_id: 166)
Ammo.create!(name: "Subsonic", price: 10, weapon_id: 166)

puts "Seeded ammos."
